services:
  service:
    image: nginx:1.24-alpine-slim
    # build:
    #   context: .
    ports:
      - 8081:80
    volumes:
      - ./public:/usr/share/nginx/html:ro
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
