apiVersion: k8s.bouyguestelecom.fr/v1alpha1
kind: PrismeConnector
metadata:
  name: "{{ .Release.Name }}-prismeconnector"
spec:
  prisme:
    enabled: true
    prod: {{ .Values.prisme.prod }}
    password: {{ .Values.prisme.password }}
    username: {{ .Values.prisme.username }}
  filters:
    st: {{ .Values.st }}
