variables:
  ST_NAME: ""
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  NO_PROXY: ""
  DOCKER_REGISTRY_HOST: registry.glouton.int.nbyt.fr
  DOCKER_REGISTRY_PATH: ""
  ARTIFACTORY_PATH: ""

default:
  image: commun/devops/ci/delivery-tools:5-LATEST
  before_script:
    - export VERSION=$(echo "$CI_COMMIT_TAG" | sed -n 's/.*@//p')
    - echo VERSION
    - sed -i "s/__VERSION_GATEWAY__/VERSION/" helms/app_name/values.yaml

include:
  - project: "COMMUN/frontoffice/templates"
    ref: 1.7.0
    file:
      - "/ci/install-playbook-template.yml"
      - "/ci/publish-container-template.yml"
      - "/ci/publish-assets-template.yml"

stages:
  - docker
  - helm
  - a7

publish_container:
  only: ["tags"]
  extends: .publish-container
  stage: docker

publish_helms:
  only: ["tags"]
  extends: .helms
  stage: helm
  variables:
    OPTIONS: "--wait-timeout=20m0s"

publish_assets:
  when: manual
  only: ["tags"]
  extends: .publish-assets
  stage: a7
  before_script:
    - export VERSION=$CI_COMMIT_TAG
  variables:
    COMPONENT_NAME: "" # a7-name
    INPUT_DIRECTORY: "" # path/to/asets/fodler
    PACKAGE_JSON: "" # path/to/package.json
