name: Publish to NPM

on:
  push:
    branches:
      - main
      - fix/*
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
      NPM_LOGIN: ${{ secrets.NPM_LOGIN }}
      NPM_PASSWORD: ${{ secrets.NPM_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Login to NPM
        run: npm login --registry=https://registry.npmjs.org/ --scope=@<username> --always-auth

      - name: Publish to NPM
        run: npm publish --workspace packages/create-spin
